// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletefollow.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteFeedFollow = `-- name: DeleteFeedFollow :execresult
DELETE FROM feed_follows
WHERE feed_follows.user_id = $1
AND feed_follows.feed_id = (
    SELECT id FROM feeds WHERE url = $2
)
`

type DeleteFeedFollowParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFeedFollow, arg.UserID, arg.Url)
}
